var GAME_LEVELS = [
  ["                                         o o                    o o                        ",
   "                                  y                                                        ",
   "              xxxxxx            yyyy                                               y       ",
   "              x    x             y                                                 y       ",
   "              x    x                    y   y                                      y       ",
   "         xxxxxx    xxxxx  xxxx         y y y               y           c          y y      ",
   "                       x!!x           y   y               yyy         xxx        y   y     ",
   "          y            x!!x    =     y            xx      y    xx    xx!xx      y     y    ",
   "     v   yyy           xvvx            o o      xx      yyy         x!!!!!x               o",
   "          y          y                               yyyyyyyyy       xx!xx                 ",
   "   x  x             yyy               xxxxx              y  v  v      xvx                  ",
   "   x!!x           yyyyy                                 y                                  ",
   "  xxxxxx            yyy               o o                                                  ",
   "                     y      x   x     xxx                                                  ",
   "                            x!!!x                         xx!!!!xx                       xx",
   "                            x!!!x     o o                 xx!!!!xx                     xx  ",
   "xx   p       xxxx       xxxxxxxxxxxxx                     xxxxxxxx       0           xx    ",
   "x            x  x         o                                              0         xx      ",
   "x            x  x                            xxxxx     v      v  xx      0       xx        ",
   "x            x  x         o                                      xxx           xx          ",
   "x    @       x  x                     c                          xxxxx       xx            ",
   "xxxxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx           xxxxxxx   xxxxxxxxxxxxxxxx",
   "                              x   x                  x!!!!!!!!!!!x     x   x               ",
   "                              x!!!x                  x!!!!!!!!!!!x     x!!!x               ",
   "                              x!!!x                  x!!!!!!!!!!!x     x!!!x               ",
   "                              xxxxx                  xxxxxxxxxxxxx     xxxxx               ",
   "                                                                                           ",
   "                                                                                           "],
  ["pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
   "pp     v       c pp      v     pp        pp   o                xxxx     xxxx                                    pp",
   "pp               pp o                    pp                     vv       vv                                     pp",
   "ppo              pp                      pp       pp    pp                                                      pp",
   "ppo                            pp        pp       pp!!!!pp                                                        ",
   "ppo                 o          pp                 pp!!!!pp          ooo              !!!!!!!!                     ",
   "xxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "yyyyyyyyy                   xxy                                                          v      !!!!!!!!!!!!!!xx  ",
   "yyyyyyyy        o   o       xxyyy                    x                                     xxxxxxxxxxxxxxxxxxxxx  ",
   "yyyyyyy                     xxyyyyy                  xyyy      xx           xx                                    ",
   "yyyyyy         xxxxxxxxxxxxxxxxxxxxxxxx          =   x         xxxx!!!!!xxxx                                      ",
   "yyyyy                           x v            x  v xxyyyyyy      xxxxxxx v     xxxxx       xxxx                 o",
   "yyyy    yy                      x              x     x               v           x xx        xxx                  ",
   "yyy       yy                    x              x     x                             xx        xxx                  ",
   "yy  xx      yy                  x              x     x                            yxx        xxx                 o",
   "y     xx      yy                x              xx    x                          oyyxx      xxxxx                  ",
   "        xx      yy              x              x     x      o  o     x   x      yyyxx        xyyyyyyyyyy         o",
   "xxx       xx        xx        xxx   xxx              x               x   x   o yyyyxx        x   vv               ",
   "            xx       xx         x   x                x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          y    xx               x   x   x               x                   c",
   "     @       x    o    x        x   x         yy     x               x   x   x    oo         x                    ",
   "o   xxx      x         x        x   x       yyyy     x               x   xxxxx   xxxxxx      x                    ",
   "xxxxx x      x         x       xx o xx    yyyyyy     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x    o    x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x                    o   yyyyyyyyyy    xx!!!!!!xx !         v    v     xx     xx                     ",
   "!!!!x x!!!!!!x    o    xxxxxxxx                     xx!!!!!!xx !                     xxxxxxx             xx       ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   ! yyyy                                    xx       ",
   "!!!!x x!!!!!!x   ooo   x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !  yyyyy                                  xx       ",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !   yyyyyyyyyyyyyyyyyyyyyyyyyyyyy         xxxxxxxxx"],
  ["v                xx     yyxxyyxxyyxxyyxxyyxxppxxyyxxyyppxxyyxxyyyyyyyyyyyyyy v      v                         ",
   "                 xx      yy            oo              yy                                                     ",
   "                 xx      yy         pppppppp           yy          =                                          ",
   "        ==       xx      yy                            yy                                                     ",
   "                 xx                     c                                                        =            ",
   "                 xx      xxxxxxxyy      o      yyxxxxxxxx                                                     ",
   "                 xx           xx        X        xx                                                           ",
   "   =             xx           xx!!!!!!!!x!!!!!!!!xx                        xxx    c   xx    yyyyyyy           ",
   "                 xx           xxxxxxxxxxxxxxxxxxxxx                        xxxxxxxxxxxxxyyyyyyyyyyyyyyyyy     ",
   "                 xx                     x                                  xxx          y                     ",
   "                oxxxxxx                 x                                  xxx          y                     ",
   "                 xx                    xxx                                 xxx          y                     ",
   "                 xx                    x x                 !!!        !!!  xxx    =     y        xxxxxxx      ",
   "v                xx                    x x                 !x!        !x!               y                     ",
   "                 xx        yyyyyyyyy xxx xxx                x          x                y                     ",
   "           y     xx                   x   x                 x   oooo   x       xxx      v                     ",
   "           y     xx                   x   x                 x          x      x!!!x                           ",
   "           yo    xx                   x   x                 xxxxxxxxxxxx       xxx                y           ",
   "          yyy   oxx                  xx   xx      x   x      x                                   yyy          ",
   "           y     xx                   x   xxxxxxxxx   xxxxxxxx              x x          o      yyyyyy        ",
   "           y     xx         yyyyyy    x   x           x                    x!!!x        xxxxxyyyyyyyyyyyyy    ",
   "           y     xx                   x o x           x                     xxx         xxxx                  ",
   "           x     xx                  xx   xx          x                                 xxxo                  ",
   "           x     xx                   x  yx= = = =    x            xxx                  xo                    ",
   "           x     xx      yyyyyy                       x           x!!!x                 xx                    ",
   "           x     xx                   x   xy   = = = =x     o      xxx       xxx        xxxo                  ",
   "v          x     xx                  xx   xx          x                     x!!!x       xxxx                  ",
   "          ox     xx           o   o  yxoooxy          x     x                xxv        xxxxx                 ",
   "        xxxx     xx                  yyxxxyx           x              x                 x!!!x                 ",
   "           x    oxx     yyyyyxxxyxxxyxxxyxxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "           x   xxxx          xyxxxyxyxyxxxyx          x!!!!!!!!!!!!!!x                                        ",
   "           x     xx          x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "           x     xx          xx           xx                                         xxx                      ",
   "  xxxxxx   x     xxo          x     x     x              oo                         x!!!x                xxx  ",
   "  x        xo    xxyyy        x    xxx    x         y          y                     yyy                 x x  ",
   "  x      yyxxx   xx           x    xxx    xxxxxxx   y    oo    y         xxxxx       yyy                   x  ",
   "  x        x     xx         oox           x         y          y         x o x       y                     x  ",
   "  xxx      x     xx       yyyyxx          x         yy        yy         x xox       y                     x  ",
   "  x        x                              x       yxxxxxxxxxxxxxxy     xxx xxx     yyy                     x  ",
   "  x        x   xxxxxxx             o o    x         v         v          x         yyy                     x  ",
   "  x        x     xxxxxxx      xx          x                             xxx       x!!!x          x         x  ",
   "  x        x     xxxxxo       x    xxx    x                             x!x        xxx          xxx        x  ",
   "  x        x     xx           x   xxxxxxxxx  x oo x    x oo x    x oo  xx!xx        v           xxx        x  ",
   "  x      @ x     xxo      !!!!x           x!!xyyyyx!!!!xyyyyx!!!!xyyyyxx!!!xx                    x         x  ",
   "  xxxxxxxxxx!!!!!xxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "!!!!!!!!!!xx!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                   xxx    xxx       xxxxx      xxx         xxx                                                ",
   "                   xxx    xxx     xxx   xxx    xxx         xxx             p      p                           ",
   "    o               xxx  xxx     xxx     xxx   xxx         xxx             yy     yy                          ",
   "                    xxx  xxx    xxx       xxx  xxx         xxx                 v                              ",
   "    o                 xxxx      xxx       xxx  xxx         xxx                 v                              ",
   "                      xxxx      xxx       xxx  xxx         xxx            yy       yy                         ",
   "    o                  xx        xxx     xxx     xxx     xxx                yy   yy                           ",
   "                       xx         xxx   xxx        xxx xxx                    yyy                             ",
   "                       xx           xxxxx            xxx                                                      ",
   "                                                                                                              ",
   "    @                                                                                                         ",
   "   xx                           xxx      xxx      xxx    xxxx    xxx  xxxx                                    ",
   "   xx                           xxx      xxx      xxx    xxxx    xxxxxx  xxxx                                 ",
   "   xx                           xxx      xxx      xxx    xxxx    xxx      xxx                                 ",
   "   xx                           xxx      xxx      xxx    xxxx    xxx       xxx                                ",
   "   xx                           xxx      xxx      xxx    xxxx    xxx       xxx                                ",
   "   xx                           xxx      xxx      xxx    xxxx    xxx       xxx                                ",
   "   xx                            xxx  xxx  xxx  xxx      xxxx    xxx       xxx                                ",
   "   xx                               xxxx     xxxx        xxxx    xxx       xxxx                               ",
   "xxxxx                                                                                                         ",
   "xxxxx                                                                                                         ",
   "xxxxx                                                                                                         ",
   "xxxxxxxxx                                                                                                     ",
   "xxxxxxxxx                                                                                                     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
